/// <reference types="cypress" />

describe('Register', function(){
    const uuid = () => Cypress._.random(0, 1e6)
    const id = uuid()
    const testname = `testname${id}`

    it('Register - Missing Last name', function(){
        cy.visit('https://parabank.parasoft.com/parabank/register.htm')
        cy.clearCookies()
        cy.get('input[id="customer.firstName"]').click().type('Diego')
        cy.get('input[id="customer.address.street"]').type('Road')
        cy.get('input[id="customer.address.city"]').type('Big City')
        cy.get('input[id="customer.address.state"]').type('Argentina')
        cy.get('input[id="customer.address.zipCode"]').type('1000')
        cy.get('input[id="customer.phoneNumber"]').type('123456789')
        cy.get('input[id="customer.ssn"]').type('1234')
        cy.get('input[id="customer.username"]').type(testname)
        cy.get('input[id="customer.password"]').type('password1')
        cy.get('input[id="repeatedPassword"]').type('password1')
        cy.get('input[value="Register"]').click()
        cy.contains('Last name is required.').should('be.visible')
    })

    it('Register - Missing First Name', function(){
        cy.visit('https://parabank.parasoft.com/parabank/register.htm')
        cy.clearCookies()
        cy.get('input[id="customer.lastName"]').click().type('Apellido')
        cy.get('input[id="customer.address.street"]').type('Road')
        cy.get('input[id="customer.address.city"]').type('Big City')
        cy.get('input[id="customer.address.state"]').type('Argentina')
        cy.get('input[id="customer.address.zipCode"]').type('1000')
        cy.get('input[id="customer.phoneNumber"]').type('123456789')
        cy.get('input[id="customer.ssn"]').type('1234')
        cy.get('input[id="customer.username"]').type('test_user')
        cy.get('input[id="customer.password"]').type('password1')
        cy.get('input[id="repeatedPassword"]').type('password1')
        cy.get('input[value="Register"]').click()
        cy.contains('First name is required.').should('be.visible')
    })

    it('Register - Missing Username & Password', function(){
        cy.visit('https://parabank.parasoft.com/parabank/register.htm')
        cy.clearCookies()
        cy.get('input[id="customer.firstName"]').click().type('Diego')
        cy.get('input[id="customer.lastName"]').click().type('Apellido')
        cy.get('input[id="customer.address.street"]').type('Road')
        cy.get('input[id="customer.address.city"]').type('Big City')
        cy.get('input[id="customer.address.state"]').type('Argentina')
        cy.get('input[id="customer.address.zipCode"]').type('1000')
        cy.get('input[id="customer.phoneNumber"]').type('123456789')
        cy.get('input[id="customer.ssn"]').type('1234')
        cy.get('input[id="repeatedPassword"]').type('password1')
        cy.get('input[value="Register"]').click()
        cy.contains('Username is required.').should('be.visible')
        cy.contains('Password is required.').should('be.visible')
    })

    it('Valid Register', function(){
        cy.visit('https://parabank.parasoft.com/parabank/register.htm')
        cy.clearCookies()
        cy.get('input[id="customer.firstName"]').click().type('Diego')
        cy.get('input[id="customer.lastName"]').click().type('Apellido')
        cy.get('input[id="customer.address.street"]').type('Road')
        cy.get('input[id="customer.address.city"]').type('Big City')
        cy.get('input[id="customer.address.state"]').type('Argentina')
        cy.get('input[id="customer.address.zipCode"]').type('1000')
        cy.get('input[id="customer.phoneNumber"]').type('123456789')
        cy.get('input[id="customer.ssn"]').type('1234')
        cy.get('input[id="customer.username"]').type(testname)
        cy.get('input[id="customer.password"]').type('password1')
        cy.get('input[id="repeatedPassword"]').type('password1')
        cy.get('input[value="Register"]').click()
        cy.contains(`Welcome ${testname}`).should('be.visible')
        cy.contains('Your account was created successfully. You are now logged in.').should('be.visible')
    })

})